apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-brixton #renamed mongo-pv to mongo-pv-brixton
  #namespace: brixton --This will be created at the cluster level.. Same name can be used by someone else also..
  labels:
    type: local
spec:
  storageClassName: document
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db/brixton"